### ISSUE TITLE
AZURE: Shared image gallery does not support replica numbers

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-azure#106]
_This issue was originally opened by @sfc-gh-lrobles in https://github.com/hashicorp/packer/issues/7990 and has been migrated to this repository. The original issue description is below._

---
[Per the azure documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/shared-image-galleries), if i want to push an image to a shared image gallery, there is no way to declare a replica count per region. The azurerm builder does not support this option in the shared_image_gallery block

I can specify which regions i want the image pushed to, but not a count

Packer version v1.4.2

**Comment by theillien** [comment]
Has this been implemented? I don't see anything in the Azure plugin docs.

**Comment by JenGoldstrich** [comment]
@theillien yes this has been added under the `target_region` block https://developer.hashicorp.com/packer/integrations/hashicorp/azure/latest/components/builder/arm#shared-image-gallery-destination there isn't a direct example in hcl in the docs but the target_region bit of the above docs explains this, closing this ticket feel free to open a new ticket if you think this documentation could be improved as this ticket is quite old
