### ISSUE TITLE
azure: Expired Password on SPN is Not Clearly Identified

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-azure#112]
_This issue was originally opened by @boumenot in https://github.com/hashicorp/packer/issues/5951 and has been migrated to this repository. The original issue description is below._

---
If an SPN's password has expired it is not very clear from the error message that this is the issue.  The error message you get is dependent upon the code path the builder takes, and the code path is dependent upon the template.  Here are some examples in case others encounter this issue.

### Creating a VHD

```text
==> azure-arm: Running builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
Build 'azure-arm' errored: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/7df44968-6690-4deb-b25d-8e04a333f5ad/resourceGroups/Default-Storage-CentralUS/providers/Microsoft.Storage/storageAccounts/packer123123/listKeys?api-version=2016-12-01: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'
```

### Create a Managed Image

```text
==> azure-arm: Running builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
Build 'azure-arm' errored: Cannot locate the managed image resource group my-packer-resource-group.
```

**Comment by JenGoldstrich** [comment]
I am not sure this is still a problem in the current plugin version, but we're dependent on our upstream auth library largely for how it handles these sorts of errors.
