### ISSUE TITLE
Packer Azure builder doesn't support choosing license

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-azure#154]
_This issue was originally opened by @maciejsikora2302 in https://github.com/hashicorp/packer/issues/11278 and has been migrated to this repository. The original issue description is below._

---
There is no way in packer to choose with which license a VM should be created.

[Official Azure guide to hybrid licensing](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/hybrid-use-benefit-licensing)

**Comment by vailenwallaces** [comment]
Is there any workaround or whatever i can do that ? So all marketplace Images that has licenses enabled like RHEL/SLES and is not PAYGO are effected by this .

**Comment by juarezr** [comment]
We had a blocking issue with the lack of license support:

- Due to governance rules, the cloud admins enabled an Azure policy that blocked virtual machines without licensing.
- `terraform` already has a [licence_type property](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#license_type) to handle this.

``` json
{
  "properties": {
    "displayName": "License AHUB",
    "policyType": "Custom",
    "mode": "All",
    "description": "Enforce license AHUB",
    "metadata": {
      "createdBy": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
      "createdOn": "2021-01-23T24:24:25.67890Z",
      "updatedBy": null,
      "updatedOn": null
    },
    "parameters": {},
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "Microsoft.Compute/imageOffer",
            "in": [
              "WindowsServer",
              "MicrosoftWindowsServer"
            ]
          },
          {
            "field": "Microsoft.Compute/licenseType",
            "exists": false
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    }
  },
  "id": "/providers/Microsoft.Management/managementGroups/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/providers/Microsoft.Authorization/policyDefinitions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "type": "Microsoft.Authorization/policyDefinitions",
  "name": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "systemData": {
    "createdBy": "cloud.amin@mycompany.com",
    "createdByType": "User",
    "createdAt": "2021-01-23T24:24:25.67890Z",
    "lastModifiedBy": "cloud.amin@mycompany.com",
    "lastModifiedByType": "User",
    "lastModifiedAt": "2021-01-23T24:24:25.67890Z"
  }
}
```

So +1

**Comment by mvwijngaarden** [comment]
Same problem here, had to made exemptions for the RG of the packerbuilder.

**Comment by michaelw730** [comment]
I've across the same issue as well on Azure.  
I've just noticed that GCP now has a similar option when selecting RHEL or SUSE - it asks if you want a BOYS or PAYG license.  
Would Packer support license_type for both GCP and Azure in a future release?
