### ISSUE TITLE
Properly handle "none" communicator settings for builder ARM

### ISSUE THREAD

**Issue by nywilken** [hashicorp/packer-plugin-azure#158]
#### Overview of the Issue

When trying to run a build of the Azure ARM builder with the communicator set to none, the deployment of the image results in a failed build. Which is not what I expected, especially if there are no defined provisioners. 

related to #155 

#### Reproduction Steps
Run a regular Packer build, with ARM credentials, on the following template. 

<details>
<summary>Test Template</summary>

```
variable "client_id" {
  type    = string
  default = "${env("ARM_CLIENT_ID")}"
}

variable "client_secret" {
  type    = string
  default = "${env("ARM_CLIENT_SECRET")}"
}

variable "resource_group_name" {
  type    = string
  default = "${env("ARM_RESOURCE_GROUP_NAME")}"
}

variable "subscription_id" {
  type    = string
  default = "${env("ARM_SUBSCRIPTION_ID")}"
}

source "azure-arm" "windows-test" {
  build_resource_group_name         = "${var.resource_group_name}"
  client_id                         = "${var.client_id}"
  client_secret                     = "${var.client_secret}"
  subscription_id                   = "${var.subscription_id}"
  communicator                      = "none"
  image_offer                       = "windowsserver"
  image_publisher                   = "microsoftwindowsserver"
  image_sku                         = "2019-datacenter"
  managed_image_name                = "PackerImageWindowsTest"
  managed_image_resource_group_name = "${var.resource_group_name}"
  os_type                           = "Windows"
  vm_size                           = "Standard_D8s_v3"
}

build {
  sources = ["source.azure-arm.windows-test"]

}
```
</details>

### Plugin and Packer version

Packer v1.7.5, Azure plugin v1.0.3`

### Log Fragments and crash.log files

```
==> Some builds didn't complete successfully and had errors:
--> azure-arm.windows-test: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"CertificateImproperlyFormatted\",\r\n        \"message\": \"The secret retrieved from https://pkrkvgp5fxv3wnh.vault.azure.net/secrets/packerKeyVaultSecret/174b6f84cb4b4b1083fc3009f0c06088 is empty string.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]

==> Builds finished but no artifacts were created.
```

**Comment by elvis-sun** [comment]
@nywilken does it support the "ssh" communicator for azure windows vm

**Comment by elvis-sun** [comment]
@nywilken I read the source code, find that
if b.config.OSType == constants.Target_Windows {
		......
        ......
        ......
		steps = append(steps,
			NewStepGetCertificate(azureClient, ui),
			NewStepSetCertificate(&b.config, ui),
			NewStepValidateTemplate(azureClient, ui, &b.config, GetVirtualMachineDeployment),
			NewStepDeployTemplate(azureClient, ui, &b.config, deploymentName, GetVirtualMachineDeployment),
			NewStepGetIPAddress(azureClient, ui, endpointConnectType),
			&communicator.StepConnectWinRM{
				Config: &b.config.Comm,
				Host: func(stateBag multistep.StateBag) (string, error) {
					return stateBag.Get(constants.SSHHost).(string), nil
				},
				WinRMConfig: func(multistep.StateBag) (*communicator.WinRMConfig, error) {
					return &communicator.WinRMConfig{
						Username: b.config.UserName,
						Password: b.config.Password,
					}, nil
				},
			},
			&commonsteps.StepProvision{},
			NewStepGetOSDisk(azureClient, ui),
			NewStepGetAdditionalDisks(azureClient, ui),
			NewStepPowerOffCompute(azureClient, ui),
			NewStepSnapshotOSDisk(azureClient, ui, &b.config),
			NewStepSnapshotDataDisks(azureClient, ui, &b.config),
			NewStepCaptureImage(azureClient, ui),
			NewStepPublishToSharedImageGallery(azureClient, ui, &b.config),
		)
	}
       ssh communicator not supported in azure windows???
       my understanding is correct???

**Comment by elvis-sun** [comment]
@nywilken @SwampDragons
Have some solution to support ssh communicator in azure windows vm?
Look forwrd to your reply.

**Comment by TheBlackMini** [comment]
Any update to this issue?

**Comment by JenGoldstrich** [comment]
Closing this as stale behavior, @nywilken feel free to open a new issue if you think this is still impacting us, for folks wanting SSH on Windows this was added in the last year :)
