### ISSUE TITLE
Attempting to build a Windows host using "communicator = none", packer crashes

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-azure#170]
_This issue was originally opened by @haggis-supper in https://github.com/hashicorp/packer/issues/11396 and has been migrated to this repository. The original issue description is below._

---
I have a secure windows image where winRM is disabled. 
To get around this issue I was attempting to do the following
1. Get packer to automatically create a log file when executed using  "export PACKER_LOG=1;export PACKER_LOG_PATH=newlog; packer ..."
2. Use a local shell script to pull the temporary packer build hostname and resource group from the created log 

  "provisioners": [
   {
      "type": "shell-local",
      "execute_command": ["bash", "-c", "{{.Script}} -L newlog"],
      "script": "./scripts/test.sh"
  }]
 3. As part of the log, use the "az vm run-command invoke --command-id RunpowerShellScript " to run commands on the host using the hostname and resourcename my script collects.

This should allow me to enable WinRm using powershell command and then sysprep the image after.

By default when you build a windows box the communicator is set to WinRM, if i set it to "none" packer crashes.

Attached is the "packer.log" file the crash create
[crash.log](https://github.com/hashicorp/packer/files/7538413/crash.log)

**Comment by nywilken** [comment]
Closing as this issue is being tracked in #158
