### ISSUE TITLE
Failed to communicate with azure windows vm by ssh

### ISSUE THREAD

**Issue by elvis-sun** [hashicorp/packer-plugin-azure#178]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Failed to communicate with azure windows vm by ssh.

the error is below:
==> azure-arm: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"CertificateImproperlyFormatted\",\r\n        \"message\": \"The secret retrieved from https://pkrkvgcaml1wusp.vault.azure.net/secrets/packerKeyVaultSecret/6536e43a77fc4869b2878ab146c82e26 is empty string.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]

### Plugin and Packer version

packer version：1.7.8

### Simplified Packer Buildfile

{
    "builders": [{
      "type": "azure-arm",

      "subscription_id": "52f5cddc-7a86-4f9f-9b52-78b0f723eb32",

      "managed_image_resource_group_name": "RG-Test22-2022",
      "managed_image_name": "packer-vm09-script",
  
      "os_type": "Windows",

      "shared_image_gallery": {
        "subscription": "52f5cddc-7a86-4f9f-9b52-78b0f723eb32",
        "resource_group": "RG-Test22-2022",
        "gallery_name": "compute_gallery",
        "image_name": "SSH_Base_Image_20220119",
        "image_version": "1.0.2"
      },
      "shared_image_gallery_destination": {
        "subscription": "52f5cddc-7a86-4f9f-9b52-78b0f723eb32",
        "resource_group": "RG-Test22-2022",
        "gallery_name": "compute_gallery",
        "image_name": "SSH_Base_Image_20220119",
        "image_version": "1.0.2",
        "replication_regions": ["East Asia"]
     },
     "communicator": "ssh",
     "ssh_timeout": "1h5m2s",
     "ssh_disable_agent_forwarding": true,

      "azure_tags": {
          "dept": "Engineering",
          "task": "Image deployment"
      },
      "build_resource_group_name": "RG-Test22-2022",
      "cloud_environment_name": "Public",
      "vm_size": "Standard_B2s"
    }],
    "provisioners": [{
      "type": "file",
      "destination": "C:\\",
      "source": "D:\\test\\pilotrun_image_maker.zip"
    },{
      "type": "powershell",
      "inline": [
        "Write-Host 'Begin to Configure System'",
        "Expand-Archive -Path C:\\pilotrun_image_maker.zip -DestinationPath C:\\",
        "Set-Location -Path C:\\",
        "C:\\pilotrun_image_maker\\image_manager.ps1",
        "Write-Host 'Generalize System'",
        "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
        "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
      ]
    }]
  }

### Operating system and Environment details

OS Version：Windows Server 2019 Server DataCenter

### Log Fragments and crash.log files

==> azure-arm: Running builder ...
==> azure-arm: Getting tokens using device flow
==> azure-arm: Getting token for https://management.azure.com/
==> azure-arm: Loading auth token from file: C:\Users\Administrator\.azure\packer\oauth-5c7d0b28-bdf8-410c-aa93-4df372b16203mgmt.json
==> azure-arm: Auth token found in file: C:\Users\Administrator\.azure\packer\oauth-5c7d0b28-bdf8-410c-aa93-4df372b16203mgmt.json
==> azure-arm: Azure token expired. Saving the refreshed token...
==> azure-arm: Getting tokens using device flow
==> azure-arm: Getting token for Vault resource
==> azure-arm: Loading auth token from file: C:\Users\Administrator\.azure\packer\oauth-5c7d0b28-bdf8-410c-aa93-4df372b16203vault.json
==> azure-arm: Auth token found in file: C:\Users\Administrator\.azure\packer\oauth-5c7d0b28-bdf8-410c-aa93-4df372b16203vault.json
==> azure-arm: Azure token expired. Saving the refreshed token...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
==> azure-arm: WARNING: Zone resiliency may not be supported in eastasia, checkout the docs at https://docs.microsoft.com/en-us/azure/availability-zones/
==> azure-arm: Getting source image id for the deployment ...
==> azure-arm:  -> SourceImageName: '/subscriptions/52f5cddc-7a85-4f9f-8b52-68b0f723eb32/resourceGroups/RG-SUNLEI22-2022/providers/Microsoft.Compute/virtualMachines/sunlei22-vm-ssh-test'
==> azure-arm: Using existing resource group ...
==> azure-arm:  -> ResourceGroupName : 'RG-Test22-2022'
==> azure-arm:  -> Location          : 'eastasia'
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'RG-Test22-2022'
==> azure-arm:  -> DeploymentName    : 'pkrdpgcaml1wusp'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'RG-Test22-2022'
==> azure-arm:  -> DeploymentName    : 'kvpkrdpgcaml1wusp'
==> azure-arm:
==> azure-arm: Getting the certificate's URL ...
==> azure-arm:  -> Key Vault Name        : 'pkrkvgcaml1wusp'
==> azure-arm:  -> Key Vault Secret Name : 'packerKeyVaultSecret'
==> azure-arm:  -> Certificate URL       : 'https://pkrkvgcaml1wusp.vault.azure.net/secrets/packerKeyVaultSecret/6536e43a77fc4869b2878ab146c82e26'
==> azure-arm: Setting the certificate's URL ...
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'RG-Test22-2022'
==> azure-arm:  -> DeploymentName    : 'pkrdpgcaml1wusp'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'RG-Test22-2022'
==> azure-arm:  -> DeploymentName    : 'pkrdpgcaml1wusp'
==> azure-arm: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"CertificateImproperlyFormatted\",\r\n        \"message\": \"The secret retrieved from https://pkrkvgcaml1wusp.vault.azure.net/secrets/packerKeyVaultSecret/6536e43a77fc4869b2878ab146c82e26 is empty string.\"\r\n      }\r\n    ]\r\n  }\r\n}"}]
==> azure-arm:

**Comment by nywilken** [comment]
Hi there @elvis-sun this is a bug on the builder. Currently the builder assumes if using Windows the communicator will be WinRM. So the builder tries to configure the instance for WinRM and fails.

**Comment by nywilken** [comment]
Related to https://github.com/hashicorp/packer-plugin-azure/issues/48

**Comment by nywilken** [comment]
@elvis-sun by chance do you have a configuration or user data file for configuration the SSH server for Windows that you would be willing to share? 

Otherwise I can create an image, setup the SSH bits, then use that for testing. Just thought I would ask.

**Comment by elvis-sun** [comment]
> by chance
@nywilken
1. download OpenSSH from https://github.com/PowerShell/Win32-OpenSSH/releases
2. install the sshd: powershell.exe -ExecutionPolicy Bypass -File install-sshd.ps1
3. config firewall inbound in powershell:   New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
4. config the sshd service style in powershell:   Set-Service sshd -StartupType Automatic

**Comment by elvis-sun** [comment]
> @elvis-sun by chance do you have a configuration or user data file for configuration the SSH server for Windows that you would be willing to share?
> 
> Otherwise I can create an image, setup the SSH bits, then use that for testing. Just thought I would ask.

@nywilken 
as to azure arm builder, it will work after making changes below:

1. builder\azure\arm\builder.go
modify the code as follow , when b.config.OSType is constants.Target_Windows
                steps = append(steps,
			NewStepGetCertificate(azureClient, ui),
			NewStepSetCertificate(&b.config, ui),
			NewStepValidateTemplate(azureClient, ui, &b.config, GetVirtualMachineDeployment),
			NewStepDeployTemplate(azureClient, ui, &b.config, deploymentName, GetVirtualMachineDeployment),
			NewStepGetIPAddress(azureClient, ui, endpointConnectType),
		)

		ui.Say("Communicator type: ")
		ui.Say(b.config.Comm.Type)

		if strings.EqualFold(b.config.Comm.Type, "ssh") {
			steps = append(steps,
				&communicator.StepConnectSSH{
					Config:    &b.config.Comm,
					Host: lin.SSHHost,
					SSHConfig: b.config.Comm.SSHConfigFunc(),
				},
			)
		} else {
			steps = append(steps,
				&communicator.StepConnectWinRM{
					Config: &b.config.Comm,
					Host: func(stateBag multistep.StateBag) (string, error) {
						return stateBag.Get(constants.SSHHost).(string), nil
					},
					WinRMConfig: func(multistep.StateBag) (*communicator.WinRMConfig, error) {
						return &communicator.WinRMConfig{
							Username: b.config.UserName,
							Password: b.config.Password,
						}, nil
					},
				},
			)
		}
		steps = append(steps,
			&commonsteps.StepProvision{},
			NewStepGetOSDisk(azureClient, ui),
			NewStepGetAdditionalDisks(azureClient, ui),
			NewStepPowerOffCompute(azureClient, ui),
			NewStepSnapshotOSDisk(azureClient, ui, &b.config),
			NewStepSnapshotDataDisks(azureClient, ui, &b.config),
			NewStepCaptureImage(azureClient, ui),
			NewStepPublishToSharedImageGallery(azureClient, ui, &b.config),
		)

2. builder\azure\arm\config.go
    a.   modify the code in the function setUserNamePassword as follow:

        if c.Comm.SSHPassword == "" {
		c.Comm.SSHPassword = c.Password
	}
	c.Password = c.Comm.SSHPassword

    b.  add the code in the function setSshValues as follow:
       cert, err := c.createCertificate()
	c.winrmCertificate = cert
	if err != nil {
	}
3. builder\azure\arm\step_deploy_template.go
    modify the code in the deployTemplate as follow:
        err = f.WaitForCompletionRef(ctx, s.client.DeploymentsClient.Client)
	if err != nil {
		s.say(s.client.LastError.Error())
	}
