### ISSUE TITLE
Add support for building from community gallery images

### ISSUE THREAD

**Issue by agrawalkshitij** [hashicorp/packer-plugin-azure#198]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description
Azure has launched community gallery images, which are public.
https://docs.microsoft.com/en-us/azure/virtual-machines/azure-compute-gallery#community 

#### Use Case(s)

This will allow  community members to easily source and modify their images from other community gallery images.

#### Potential configuration

```
```

**Comment by invidian** [comment]
https://github.com/hashicorp/packer-plugin-azure/pull/199 has been merged so I guess this can be closed?
