### ISSUE TITLE
Packer 1.8.1 :  the Shared Gallery Image to which to publish the managed image version to does not exist  error

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-azure#205]
_This issue was originally opened by @cello86 in https://github.com/hashicorp/packer/issues/11827 and has been migrated to this repository. The original issue description is below._

---
Hi all,
we're trying to automate the azure base image creation via packer and deploy them on a shared image gallery instance to share the artifacts on different subscriptions, but we receive this error when we try to push the image to the gallery:

```
==> azure-arm.rhel_byos: Running builder ...
==> azure-arm.rhel_byos: Getting tokens using client secret
==> azure-arm.rhel_byos: Getting tokens using client secret
    azure-arm.rhel_byos: Creating Azure Resource Manager (ARM) client ...
Build 'azure-arm.rhel_byos' errored after 1 second 74 milliseconds: the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group xxxx

==> Wait completed after 1 second 74 milliseconds

==> Some builds didn't complete successfully and had errors:
--> azure-arm.rhel_byos: the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group xxxx

==> Builds finished but no artifacts were created.
```

We checked the permissions and they are ok, but the problem is related to a image gallery empty. In fact the error reported below is  related to the image missing, but at the first run of packer it could be normal that the artifact is not present.

`2022/06/01 14:10:12 packer-plugin-azure_v1.0.6_x5.0_linux_amd64 plugin: 2022/06/01 14:10:12 Azure response status="404 Not Found" method="GET" request="https://management.azure.com/subscriptions/xxxxx/resourceGroups/xxxx/providers/Microsoft.Compute/galleries/xxxx/images/rhel7?api-version=2020-09-30" x-ms-request-id="5e12db78-8485-4026-8443-d701d07eb9f5" body="{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Compute/galleries/xxxx/images/rhel7' under resource group 'xxxx' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"}}"`

Could you confirm that we have to create the image manually? Why this task is required?

Thanks,
Marcello

**Comment by jeffhuenemann** [comment]
@cello86 I've just been experimenting with Packer for the first time this week, and I got hung up on the same thing at first. Here's what I figured out:
- You create the ~~Shared Image Gallery~~ Azure Compute Gallery (Terraform: [azurerm_shared_image_gallery](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/shared_image_gallery)) yourself 
- You create a VM Image definition (Terraform:  [azurerm_shared_image](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/shared_image)) within that Gallery yourself
- Running packer creates a "VM Image Version" within the Definition you created above.

Hope that helps!

**Comment by dhawal-sanghvi** [comment]
Hello @jeffhuenemann ,

I am running into same issue with packer as it failing due to "the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group".  Can you provide some insights on how to use **VM Image definition** key in the packer builder section which was created as first step? Looking at the packer build section [packer](https://www.packer.io/plugins/builders/azure/arm), I dont find this option defined or used.

`"shared_image_gallery": {
    "subscription": "00000000-0000-0000-0000-00000000000",
    "resource_group": "ResourceGroup",
    "gallery_name": "GalleryName",
    "image_name": "ImageName",
    "image_version": "1.0.0",
}`

In that case, how does packer know the image definition? Any help would be appreciated.

Thanks!!

**Comment by xenadmin** [comment]
I'm having the same issue. I created a resource group, a compute gallery and an image definition. I already captured a few VMs manually to get started, and now I want to till the gallery with new image version through packer. But I always get the error:
`--> azure-arm: the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group rg-citrix-images`
I set the following JSON code, but I have trouble combining the values with the variables, obviously, most important, where the image definition goes to:
```
"shared_image_gallery_destination": {
	"subscription": "123",
	"resource_group": "rg-citrix-images",
	"gallery_name": "cg_citrix_images",
	"image_name": "Definition-AZ-XAD-M-W10-01",
	"image_version": "1.0.2",
	"replication_regions": [
		"westeurope"
	],
	"storage_account_type": "Standard_LRS"
},
```
The gallery name is correct, but what should the image name be? I can't get my head around that one. I currently out the name of my image definition there. 
![grafik](https://user-images.githubusercontent.com/12057348/214940441-5e2c261c-601d-4b44-b9ea-630fb11a4f50.png)

**Comment by dhawal-sanghvi** [comment]
> Hello @jeffhuenemann ,
> 
> I am running into same issue with packer as it failing due to "the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group". Can you provide some insights on how to use **VM Image definition** key in the packer builder section which was created as first step? Looking at the packer build section [packer](https://www.packer.io/plugins/builders/azure/arm), I dont find this option defined or used.
> 
> `"shared_image_gallery": { "subscription": "00000000-0000-0000-0000-00000000000", "resource_group": "ResourceGroup", "gallery_name": "GalleryName", "image_name": "ImageName", "image_version": "1.0.0", }`
> 
> In that case, how does packer know the image definition? Any help would be appreciated.
> 
> Thanks!!

Solved: Thanks, I was able to fix the problem by providing Service Principal access to the Resource Group that contains the computer gallery.

**Comment by JenGoldstrich** [comment]
Closing this as solved, thanks for helping @xenadmin!
