### ISSUE TITLE
Does it support ARM64?

### ISSUE THREAD

**Issue by snnn** [hashicorp/packer-plugin-azure#210]
#### Description

Azure now has ARM VMs: https://azure.microsoft.com/en-us/updates/public-preview-arm64based-azure-vms-can-deliver-up-to-50-better-priceperformance/

But, does packer support generating images for ARM64? I tried it, then I got the following error:

==> azure-arm: ERROR: -> OperationNotAllowed : Creating an image with sourceVirtualMachine source that has CPU Architecture 'Arm64' is not supported. Please select a source resource with a supported CPU Architecture: 'x64'.

Is there a way to get it work?

#### Use Case(s)

When the ARM64 VMs becomes GA, I'm sure a lot of people will need this.

#### Potential configuration

```
```

**Comment by BriceLag** [comment]
Hello,
Since Sept 1, 2022: Azure Virtual Machines with Ampere Altra Arm–based processors are now generally available.
Have you any update ?
The azcli command to create a arm64 images is working.
Best regards,

**Comment by VladRassokhin** [comment]
Azure Console doesn't allow capturing Arm64 VMs into a managed image, only share as VM image version.
Probably another API call should be used instead of creating managed image first and then optionally converting it to a VM image version, as packer does right now.

Here's screenshot proof on Arm64 VM
<img width="584" alt="Screenshot 2022-10-12 at 14 32 10" src="https://user-images.githubusercontent.com/552079/195343676-92995c2f-ae13-46da-a611-dfb20586a103.png">

**Comment by VladRassokhin** [comment]
Sorry for the noise, GitHub doesn't remove commits overwritten by force-push.
Please see #242

**Comment by evanye** [comment]
Looks like anyone using packer to build arm64 azure images will hit this problem. @VladRassokhin any luck with your proposed fix at https://github.com/hashicorp/packer-plugin-azure/pull/242 ?

**Comment by VladRassokhin** [comment]
@evanye IDK, will take a look. Meanwhile, I'm quite happy with the local build of that plugin.

**Comment by harshavmb** [comment]
Hey @VladRassokhin ,

you may have probably seen the comment [here](https://github.com/hashicorp/packer-plugin-azure/pull/242#issuecomment-1370290322) by the reviewer. If you could respond to the comment & make changes, it would be of great help. 

We too wanted to build arm64 images so don't want to reinvent the wheel. 

Your help is much appreciated!
