### ISSUE TITLE
Azure-arm Packer doesn't clean up additional disk

### ISSUE THREAD

**Issue by jkasnar2410** [hashicorp/packer-plugin-azure#215]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue
There seems to be an issue with Packer not deleting an additional disk that was attached to the build machine, regardless if the build fails or not. **The issue seems to only be happening when a custom resource group is used for the build.** The OS disk gets deleted normally, but the additional one is always left there in an unattached state. There is no error during clean up, so it seems to be that it doesn't even try to delete the additional disk.
If a build is run when no resource group is specified (packer created a new one), the disk gets normally deleted.
This seems to be the same issue already reported that was apparently fixed 2 years ago:
https://github.com/hashicorp/packer/issues/10268
https://github.com/hashicorp/packer/pull/10713

#### Reproduction Steps

1. Write a simple Packer template for azure-arm that uses existing resource group
2. Wait for the build to finish or fail (it's irelevant )
3. Check Azure portal and see the disk still there in an unattached state

### Packer version

1.8.2 (latest ATM)

### Simplified Packer Template

```
source "azure-arm" "appliance-azure-image-2disks" {
  image_offer                            = "rockylinux"
  image_publisher                        = "erockyenterprisesoftwarefoundationinc1653071250513"
  image_sku                              = "free"
  managed_image_name                     = "test-disk-build"
  managed_image_resource_group_name      = "<< my_resource_group >>"
  os_type                                = "Linux"
  subscription_id                        = "<< my_subscription_id"
  tenant_id                              = "<< my_tenant_id >>"
  vm_size                                = "Standard_D4as_v4"
  os_disk_size_gb                        = "50"
  build_resource_group_name              = "<< my_resource_group >>"
  virtual_network_name                   = "<< my_virtual_network >>"
  virtual_network_subnet_name            = "<< my_subnet >>"
  virtual_network_resource_group_name    = "<< my_resource_group >>"
  private_virtual_network_with_public_ip = "true"
  skip_create_image                      = "false"
  custom_resource_build_prefix           = "ado"
  managed_image_storage_account_type     = "Premium_LRS"
  disk_additional_size                   = [100]
  plan_info {
    plan_name      = "free"
    plan_product   = "rockylinux"
    plan_publisher = "erockyenterprisesoftwarefoundationinc1653071250513"
  }
}

```

### Operating system and Environment details

Fedora 36

### Log Fragments and crash.log files

In the log it is visible that the OS disk is deleted, but there are no mentions of additional disk being deleted.

```
==> azure-arm.appliance-azure-image-2disks: Attempting deletion -> Microsoft.Network/publicIPAddresses : 'adoipgwak3'
==> azure-arm.appliance-azure-image-2disks:  Deleting -> Microsoft.Compute/disks : '/subscriptions/{{ my_subscription }}/resourceGroups/{{ my_resource_group }}/providers/Microsoft.Compute/disks/adoosgwak3'
==> azure-arm.appliance-azure-image-2disks: Removing the created Deployment object: 'adodpgwak3'
```

OS disk adoosgwak3 is deleted, but additional disk adoddgwak3-1 is not deleted.

**Comment by jkasnar2410** [comment]
@nywilken Thanks you. Do you happen to know when the next plugin version is scheduled to be released?

**Comment by nywilken** [comment]
So generally speaking we aim to release every two weeks, if not weekly, to get new changes out the door. We have to troubleshoot this request a bit before I can give a timeline on the release.  I'm shooting for a two week window but I ask for a little room, as deleting on the plugin has been a bit of tricky thing. 


cc agrawalkshitij for any insight on this issue.
