### ISSUE TITLE
support to add expiration date when setting winrm certificate in the KeyVault

### ISSUE THREAD

**Issue by LifengXiang** [hashicorp/packer-plugin-azure#235]
When we enforce Azure policy on KeyVault that Secrets should have expiration dates set, following error happened.

azure-arm.azure: Setting the certificate in the KeyVault...
azure-arm.azure: Error setting winrm cert in custom keyvault: Failed to set secret to test/packerKeyVault, HTTP status code=403 (Forbidden)

**Comment by leshicodes** [comment]
+1 We do the same thing in our Tenant. this would be an amazing feature to have.

**Comment by srikanthv18** [comment]
any update on this?

**Comment by JenGoldstrich** [comment]
This will be fixed with the release in v2.0.0 code for which has been done in this PR https://github.com/hashicorp/packer-plugin-azure/pull/326

**Comment by dawsonar802** [comment]
@JenGoldstrich , is there an expected release date for v2.0.0?  I am running into this issue and need to either try and resolve to grant an exception for policy that is blocking it.

**Comment by JenGoldstrich** [comment]
@dawsonar802 Unless we run into any unexpected issues during our testing hopefully in 1-2 weeks
