### ISSUE TITLE
New use_interactive_auth option is a not documented as a breaking change

### ISSUE THREAD

**Issue by jamespic** [hashicorp/packer-plugin-azure#238]
#### Overview of the Issue

PR #143 (which was merged as part of 1.3.0) introduced a new option, use_interactive_auth. Prior to this change, interactive authentication was the default, if no additional config is provided. After this change, managed identity is the default if no additional config is provided. This leads to a new and surprising error message when building from a development workstation.

This change to defaults is reasonable, and the bug that this merge fixes is worth fixing, but this is a breaking change that is not called out in the release history.

### Plugin and Packer version

Plugin 1.3.1, Packer 1.8.3

### Simplified Packer Buildfile

```
source "azure-arm" "example" {
  subscription_id = "mysubscription"

  os_type = "Linux"
  image_publisher = "Canonical"
  image_offer = "0001-com-ubuntu-server-focal"
  image_sku = "20_04-lts-gen2"

  managed_image_name = "example"
  managed_image_resource_group_name = "myresourcegroup"

  build_resource_group_name = "myresourcegroup"

  vm_size = "Standard_B1s"
}
```

**Comment by nywilken** [comment]
Thanks for reporting. We will take a look.

**Comment by JenGoldstrich** [comment]
Hey @jamespic  thanks for calling this out,

I agree this is definitely an undocumented breaking change, sorry about the inconvenience this caused you! I have updated the [release notes](https://github.com/hashicorp/packer-plugin-azure/releases/tag/v1.3.0) for v1.3.0 to capture this
