### ISSUE TITLE
Create child image using Packer HCP registry in Azure

### ISSUE THREAD

**Issue by valeriocapponi** [hashicorp/packer-plugin-azure#251]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Be able to create child image using Packer HCP registry as source like is described here: https://developer.hashicorp.com/packer/tutorials/hcp-get-started/hcp-create-child-image

The example only talks about AWS. in the azure-arm plugin is not possible to specify the id of the image to use. 

I tried to use community_gallery_image_id and direct_shared_gallery_image_id but it doesn't work.

#### Use Case(s)

To shorten the deployment time, using intermediate images like:

Steps:

1. A golden image is build with packer and sourced by the Azure standard images and stored in the HCP registry
2. An intermediate image is built then using the Golden Image from the HCP registry 

#### Potential configuration

```
```

**Comment by nywilken** [comment]
Hi @valeriocapponi thanks for reaching out. The Azure builder does work differently then the AWS builder so providing the source image information from a HCP Packer registry is handled a little differently. If you could provide us with a sample of your template configuration we should be able to help find a path forward. 

I created a working example of how this is done using the custom managed image attributes but it may not solve your issue if you are using a different type of source image configuration. Here is the link to the the example https://github.com/nywilken/hcp_packer_examples/blob/main/azure-arm/custom-image/source.pkr.hcl

**Comment by valeriocapponi** [comment]
Hello! Thank you for the quick reply. We tested this finally and it works! May suggest to add this in the documentation?
