### ISSUE TITLE
"shared_image_gallery_destination" should be able to process specialized images

### ISSUE THREAD

**Issue by xenadmin** [hashicorp/packer-plugin-azure#262]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Hi Everybody, just getting started with packer. 
My goal is to automatically create Golden Master images for Citrix DaaS on Azure (aka Citrix Cloud).  I created an Azure Compute Gallery (formerly Shared Image Gallery) and added a definition to it, which only allowed specialized images. This is a requirement by Citrix, as Citrix boots up and specialized image and does the sysprep itself (_"Not generalized: The image must not be generalized."_). (https://docs.citrix.com/en-us/citrix-daas-azure/master-images.html#import-an-image-from-azure) In my Packer template, I did not add a sysprep step, because of the former requirement. When Packer then tries to add the not-sysprepped image to the compute gallery, it fails with the following error:

```
"Cannot create Gallery Image Version from: '/subscriptions/x-x-x/resourceGroups/rg-packer-images/providers/Microsoft.Compute/images/packer-win10-22h2-avd' since the OS State in the parent gallery image ('Specialized') is not 'Generalized'."
```

Just to try it out, I re-created the image definition and set it to generalized, without altering the packer template, which would still not sysprep. The packer template would finish successfully now, but the VMs created from the compute gallery are not useable (at least to my testing). But this made the template work. 

#### Use Case(s)

As far as I can tell, Packer does not allow generating specialized images for an Azure compute gallery directly, which is a missing feature for us. Citrix is shifting its focus from snapshots towards the Azure compute gallery for Golden master image management. My current workaround is to not use Packer for the Gallery, but to create a snapshot from the Packer build, which I then import with a PowerShell script to the compute gallery as a specialized image after the Packer build. It would be much more convenient, if I could skip that part altogether and not let Packer tell me, what I can upload into an Azure compute gallery with a proper definition applied (no offense!)

#### Potential configuration

```
"shared_image_gallery_destination": {
	"subscription": "x-x-x",
	"resource_group": "rg-packer-images",
	"gallery_name": "cg_citrix_imagfes",
	"image_name": "XAD-W10-01",
	"image_version": "{{user `imageversion`}}",
	"replication_regions": [
		"westeurope"
	],
	"storage_account_type": "Standard_LRS"
},
```

**Comment by cloudvant** [comment]
Using a  specialized Shared Image Gallery image as a source, so that it can be patched is not working. See https://github.com/hashicorp/packer-plugin-azure/issues/307
