### ISSUE TITLE
Disk Encryption Set ID does not work for Replicated Regions

### ISSUE THREAD

**Issue by JenGoldstrich** [hashicorp/packer-plugin-azure#264]
I realized after releasing v1.4.0 that setting a `disk_encryption_set_id` will not work when replicating a SIG image to multiple regions, since Disk Encryption Set's can only exist in one region if you're replicating a shared image definition to a different region, that DES won't exist in that region, this should be fixed adding an extra field to shared_image_gallery_destination, for these replication regions encryption IDs, it should take in an array of strings that are at the same index of the replication region, something like this in HCL

```
shared_image_gallery_destination {
     resource_group = "test"
     gallery_name = "gallery"
     image_name = "image"
     image_version = "1.0.0"
     replication_regions  = ["East US", "East US 2", "East US 3"]
     replication_region_disk_encryption_set_ids = ["encryption-for-east-us-id", "encryption-for-east-us-id-2", "encryption-for-east-us-3-id"]
}
```

**Comment by markti** [comment]
this does in fact look like a bug... as disk encryption sets are regional, it looks like you need to provide a different one for each region you replicate to. 

The code here seems to be the problem:

https://github.com/hashicorp/packer-plugin-azure/blob/10a55d5fbd83bf263dc3d6f2a6ab8cd4d7f2a1b7/builder/azure/arm/step_publish_to_shared_image_gallery.go#L33

the attribute "disk_encryption_set_id" is mapped to variable "DiskEncryptionSetId" but it is set at the builder level and not specified for each geo-replicated region.

**Comment by darrens280** [comment]
Adding support for `DiskEncryptionSetId` in Azure Plugin v2.0.3 (released last night), using new syntax of the `target_region` (with one replicated region) block to replace the deprecated `replicated_regions` attribute inside `shared_image_gallery_destination`, this breaks the pipeline, at the point where the Image is being captured into the Compute Gallery, with the error below. We don't use Disk Encryption Sets, but it seems to be mandatory (?)

```
ERROR: -> LinkedInvalidPropertyId : Property id '' at path 'properties.publishingProfile.targetRegions[0].encryption.osDiskImage.diskEncryptionSetId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'
```

When I revert and use Azure Plugin v2.0.2, and `replicated_regions`, then all works fine.

Thanks
Darren

**Comment by nywilken** [comment]
> Hi. Adding support for `DiskEncryptionSetId` in Azure Plugin v2.0.3 (released last night), using new syntax of the `target_region` (with one replicated region) block to replace the deprecated `replicated_regions` attribute inside `shared_image_gallery_destination`, this breaks the pipeline, at the point after Sysprep completes, and Image is being captured into the Compute Gallery, with the error below. We don't use Disk Encryption Sets, but it seems to be mandatory (?)
> 
> ```
> ERROR: -> LinkedInvalidPropertyId : Property id '' at path 'properties.publishingProfile.targetRegions[0].encryption.osDiskImage.diskEncryptionSetId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'
> ```
> 
> When I revert and use Azure Plugin v2.0.2, and `replicated_regions`, then all works fine.
> 
> Thanks Darren

Hi @darrens280 this sounds like a regression. 

Do you have a redacted template that I can use to reproduce the issue? 

The Encryption keys should be optional but there might be something I overlooked. If you can share a template I can work on getting this fixed asap.

**Comment by nywilken** [comment]
> Hi. Adding support for `DiskEncryptionSetId` in Azure Plugin v2.0.3 (released last night), using new syntax of the `target_region` (with one replicated region) block to replace the deprecated `replicated_regions` attribute inside `shared_image_gallery_destination`, this breaks the pipeline, at the point after Sysprep completes, and Image is being captured into the Compute Gallery, with the error below. We don't use Disk Encryption Sets, but it seems to be mandatory (?)
> 
> ```
> ERROR: -> LinkedInvalidPropertyId : Property id '' at path 'properties.publishingProfile.targetRegions[0].encryption.osDiskImage.diskEncryptionSetId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'
> ```
> 
> When I revert and use Azure Plugin v2.0.2, and `replicated_regions`, then all works fine.
> 
> Thanks Darren

No template necessary. I was able to reproduce and opened up a fix for the bug. It turns out that an empty string was being sent for the encryption thus making it invalid. I'll will release the fix shortly.

**Comment by darrens280** [comment]
Ah, lovely thank you. I was just about to drop a template in here for you to review. Ok no worries. I look fwd to the fix. Many thanks for speedy response

**Comment by nywilken** [comment]
@darrens280 the fix has been released https://github.com/hashicorp/packer-plugin-azure/releases/tag/v2.0.4

Please upgrade to v2.0.4 and retest with your configuration.

**Comment by darrens280** [comment]
Hi @nywilken 
I can confirm v2.0.4 of the plugin resolves the error described previously 👍 
Many thanks for the help
