### ISSUE TITLE
ERROR: -> OperationNotAllowed : Creating an image with sourceVirtualMachine source that has CPU Architecture ‘Arm64’ is not supported. Please select a source resource with a supported CPU Architecture: ‘x64’.

### ISSUE THREAD

**Issue by smerle33** [hashicorp/packer-plugin-azure#286]
as per https://github.com/hashicorp/packer-plugin-azure/issues/287

I think that this issue should be in this issue tracker.

Do not hesitate to remove it if I am wrong.

**Comment by JenGoldstrich** [comment]
Closing this as duplicate as Wilken moved https://github.com/hashicorp/packer-plugin-azure/issues/287 to this repo
