### ISSUE TITLE
ERROR: -> OperationNotAllowed : Creating an image with sourceVirtualMachine source that has CPU Architecture ‘Arm64’ is not supported. Please select a source resource with a supported CPU Architecture: ‘x64’.

### ISSUE THREAD

**Issue by smerle33** [hashicorp/packer-plugin-azure#287]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
When trying to generate an ARM64 ubuntu image on AZURE, it fail with : ERROR: -> OperationNotAllowed : Creating an image with sourceVirtualMachine source that has CPU Architecture ‘Arm64’ is not supported. Please select a source resource with a supported CPU Architecture: ‘x64’.

#### Reproduction Steps

Steps to reproduce this issue

clone https://github.com/smerle33/packer_arm/tree/main

make sure to set the environment variable : AZURE_SUBSCRIPTION_ID
this repo is using `use_interactive_auth`

packer init .
packer build .

### Packer version

From `packer version`
`Packer v1.8.6`

### Simplified Packer Template

```
variable "azure_subscription_id" {
  type    = string
  default = env("AZURE_SUBSCRIPTION_ID")
}

variable "azure_region" {
  type    = string
  default = "East US"
}

packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = ">= 1.4.2"
    }
  }
}

locals {
  date = formatdate("HHmm", timestamp())
}

source "azure-arm" "ubuntu-arm-lts" {
  subscription_id      = var.azure_subscription_id
  use_interactive_auth = true
  os_type              = "Linux"
  image_offer          = "0001-com-ubuntu-server-jammy"
  image_publisher      = "canonical"
  image_sku            = "22_04-lts-arm64"

  vm_size        = "Standard_D4ps_v5"
  ssh_username   = "ubuntu"
  ssh_agent_auth = false

  azure_tags = {
    dept = "JenkinsOSS"
    task = "Image deployment"
  }
}

build {
  source "source.azure-arm.ubuntu-arm-lts" {
    location                          = var.azure_region
    managed_image_name                = "jenkins_test_ARM64_${local.date}"
    managed_image_resource_group_name = "dev-packer-images"
  }
}

```

### Operating system and Environment details

ARM64

**Comment by smerle33** [comment]
Hi jenna,
Thanks for the help but I still cannot manage it ... I tried this : 

```
source "azure-arm" "ubuntu-arm-lts" {
  subscription_id      = var.azure_subscription_id
  use_interactive_auth = true

  os_type              = "Linux"
  image_offer          = "0001-com-ubuntu-server-jammy"
  image_publisher      = "canonical"
  image_sku            = "22_04-lts-arm64"

  vm_size        = "Standard_D4ps_v5"
  location           = "East US"
  ssh_username   = "ubuntu"
  ssh_agent_auth = false

  azure_tags = {
    dept = "JenkinsOSS"
    task = "Image deployment"
  }

  # Where to export the image
  shared_image_gallery_destination {
    subscription        = var.azure_subscription_id
    resource_group      = "dev-packer-images"
    gallery_name        = "dev_packer_images"
    image_name          = "smerle-test-arm64"
    image_version       = var.image_version
    storage_account_type = "Standard_LRS"
  }
}

build {
  sources = ["source.azure-arm.ubuntu-arm-lts"]
}

```

but still get a `==> azure-arm.ubuntu-arm-lts: ERROR: -> OperationNotAllowed : Creating an image with sourceVirtualMachine source that has CPU Architecture 'Arm64' is not supported. Please select a source resource with a supported CPU Architecture: 'x64'.`

I don't get it ... I removed the whole managed image part ... sounds like your snippet with our own gallery ...

Sorry, it's probably a silly thing that I miss ...

Stéphane

**Comment by JenGoldstrich** [comment]
All good friend, I think that you just need to set your VM Image definition to a v2 VM generation, and then set the CPU architecture to Arm64 when defining the VM Image Definition, I believe Azure only lets you push x86 images to x86 SIG images
![Screenshot 2023-04-11 at 7 42 55 AM](https://user-images.githubusercontent.com/23503014/231199210-fcad887f-28a0-4445-8087-86e6c823c82e.png)
Lemme know if you're still unable to deploy this image

**Comment by smerle33** [comment]
even with the gen2 tag on the name `image_sku            = "22_04-lts-arm64-gen2"` 
I get : `==> azure-arm.ubuntu-arm-lts: ERROR: -> OperationNotAllowed : Creating an image with sourceVirtualMachine source that has CPU Architecture 'Arm64' is not supported. Please select a source resource with a supported CPU Architecture: 'x64'.`

the gallery is already gen 2 compatible  (see screen shot) 
![image](https://user-images.githubusercontent.com/95630726/231221845-8ad28312-06e9-47e1-bc93-743044bceb1d.png)

the Azure compute gallery named `dev_packer_images` got multiple sub-folder with one of witch is the arm one ...

I did tried to change `gallery_name        = "dev_packer_images"` to `gallery_name        = "dev_packer_images/jenkins-agent-ubuntu-22.04-arm64"` with no success 

still stuck here ....

**Comment by JenGoldstrich** [comment]
Huh 🤔, just to make sure when you created the VM Image Definition inside of the compute gallery for this image, did you define the VM Architecture as Arm64? 
![Screenshot 2023-04-11 at 9 19 53 AM](https://user-images.githubusercontent.com/23503014/231226199-82df5cf4-4148-4413-8f93-122f1c60b7af.png)
