### ISSUE TITLE
Build custom VM image for Confidential VMs

### ISSUE THREAD

**Issue by surajssd** [hashicorp/packer-plugin-azure#290]
How to build and publish images that can run confidential VMs? There are default images that I can use to run CVMs. But I would like to make some modifications before running CVMs. If I build an image using the published CVM images, I cannot start a CVM because managed images are not supported.

```hcl
...
  image_publisher = "Canonical"
  image_offer     = "0001-com-ubuntu-confidential-vm-jammy"
  image_sku       = "22_04-lts-cvm"
...
```

But I think there is a way to create a `image-definition` with feature `SecurityType=ConfidentialVmSupported` which can be used to publish custom CVM images.

How can I use packer to do the same?

**Comment by surajssd** [comment]
For the sake of completion here is how you would do it. Create a "Shared Image Gallery" and "Gallery Image definition" that supports confidential VM. And on the packer side ask it to push the created image to this shared image gallery.

Following commands show how to create "shared image gallery" & "image definition":

```bash
# These two names match with the packer input.
export GALLERY_NAME="surajCVMImageGallery"
export GALLERY_IMAGE_DEF_NAME_COCO=cc-image

az sig create \
    --gallery-name "${GALLERY_NAME}" \
    --resource-group "${RESOURCE_GROUP}" \
    --location "${LOCATION}"

az sig image-definition create \
    --resource-group $RESOURCE_GROUP \
    --gallery-name $GALLERY_NAME \
    --gallery-image-definition $GALLERY_IMAGE_DEF_NAME_COCO \
    --publisher myPublisher \
    --offer myOffer \
    --sku mySKU \
    --os-type Linux \
    --os-state Generalized \
    --hyper-v-generation V2 \
    --location "${LOCATION}" \
    --architecture x64 \
    --features SecurityType=ConfidentialVmSupported
```

And here is the snipped I added to packer config:

```hcl
source "azure-arm" "ubuntu" {
...
  shared_image_gallery_destination {
      subscription = "${var.subscription_id}"
      resource_group = "${var.resource_group}"
      gallery_name = "surajCVMImageGallery"
      image_name = "cc-image"
      image_version = "0.0.1"
      storage_account_type = "Standard_LRS"
  }
...
}
```

But I think it would be neat to have a way to create the shared image gallery using packer.

**Comment by surajssd** [comment]
For now I am able to get the image built without specifying anything for the tpm. As in leaving the field `vTpmEnabled` blank / null. And use machine types `Standard_D2as_v5` or `Standard_D4as_v5`.

I reported my hypothesis here: https://github.com/confidential-containers/cloud-api-adaptor/issues/799#issue-1661711617

**Comment by JenGoldstrich** [comment]
Hey @surajssd, I know this ticket is a bit old but Confidential VM support was added in v2.0.5 of the plugin, please feel free to open a new issue if you have trouble using it
