### ISSUE TITLE
Examples section is outdated

### ISSUE THREAD

**Issue by oliverlabs** [hashicorp/packer-plugin-azure#309]
Examples section is outdated. Would it be useful if I submitted a PR with a more recent example using pkr.hcl and all the good auto.pkrvars.hcl stuff?

**Comment by JenGoldstrich** [comment]
Hey Oliver, I have a dozen or so templates that I use personally and have been meaning to go through them and add them to our example files on the repo, they are really out of date as you mention.  I'd definitely appreciate any PRs to add some new examples!
