### ISSUE TITLE
FEATURE: Add Shallow option for publishing to ACG

### ISSUE THREAD

**Issue by oliverlabs** [hashicorp/packer-plugin-azure#313]
Could you please add the `--replication-mode Shallow` support for publishing to ACG?

As per Az CLI documentation [here](https://learn.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries?tabs=azure-cli#shallow-replication).

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

As per Az CLI documentation [here](https://learn.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries?tabs=azure-cli#shallow-replication).

#### Use Case(s)

Faster iterations between Packer runs for developers! Average replication takes 15-20 minutes.

#### Potential configuration

```
```

**Comment by oliverlabs** [comment]
@JenGoldstrich

**Comment by yghia** [comment]
Looking forward to this change. 
Replication mode set to shallow speeds up our build time significantly as publishing image with full replication takes close to 10-15x more time compared to shallow replication.

**Comment by oliverlabs** [comment]
Hi @yghia. No, I just gave up on the idea and closed the long standing request.

**Comment by yghia** [comment]
:disappointed:
I would have loved if this feature request could be revived.

**Comment by JenGoldstrich** [comment]
Hey friends, just to be clear I am intending to follow up and finish that PR, apologies I have been busy with other projects. I will update this issue when I have an update,  all that needs to be done is fix up some unit tests and modify one acceptance test to use shallow replication, I am planning to address all open PRs within the next few weeks.

**Comment by oliverlabs** [comment]
woo-hoo! @JenGoldstrich
