### ISSUE TITLE
Update docs related to interactive (device code) authentication

### ISSUE THREAD

**Issue by ntabris** [hashicorp/packer-plugin-azure#354]
The section in https://github.com/hashicorp/packer-plugin-azure/blob/main/docs/README.md about "Interactive User Authentication" has not been updated based on changes in v2.0.0 and still says to use `use_interactive_auth`.

Here's relevant text from [release notes](https://github.com/hashicorp/packer-plugin-azure/releases/tag/v2.0.0):

> Interactive (Device Code) Authentication
>
> In Azure Packer plugin Packer v2.0.0 we have removed support for the authentication option use_interactive_auth aka Device Code login, users can still use device code login through the Azure CLI az login –use-device-code and then using the use_azure_cli_auth authentication option.

**Comment by JenGoldstrich** [comment]
Resolved in newest commit, thanks for reporting this inconsistency!
