### ISSUE TITLE
Datasource isn't evaluated before source and build

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/packer-plugin-azure#448]
#### Overview of the Issue

I have a Datasource plugin that I'm expecting to run and generated a value that I want to use in my source object.  I created a demo project that works fine with just the datasource extension but when I added the datasource and the local var it doesn't set the source var as I expected.

#### Reproduction Steps

```
packer build .
```

### Plugin and Packer version

```
Packer v1.11.2

packer-plugin-ansible_v1.1.1_x5.0_darwin_arm64
azure/packer-plugin-azure_v2.1.8_x5.0_darwin_arm64
docker/packer-plugin-docker_v1.0.10_x5.0_darwin_arm64
github.com/joomcode/external/packer-plugin-external_v0.0.3_x5.0_darwin_arm64
```

### Simplified Packer Buildfile

```
packer {
  required_plugins {
    azure = {
      version = "~> 2"
      source  = "github.com/hashicorp/azure"
    }
    external = {
      version = ">= 0.0.3"
      source  = "github.com/joomcode/external"
    }
  }
}

data "external-raw" "new-version" {
  program = ["echo", "1.1.1" ]
}

locals {
  new_version = data.external-raw.new-version.result
}

source "azure-arm" "devops" {

  shared_image_gallery_destination {

      image_version = local.new_version
  }
}

build {
  sources = ["source.azure-arm.devops"]
  provisioner "shell-local" {
    inline = [
      "echo The New Version is ${data.external-raw.new-version.result}",
    ]
  }
}
```

### Operating system and Environment details

MacOS

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by DevopsMercenary** [comment]
This is a mini version of my demo project showing the datasource working.

```
packer {
  required_plugins {
    external = {
      version = ">= 0.0.3"
      source  = "github.com/joomcode/external"
    }
  }
}

### Datasources

data "external-raw" "new-version" {
  program = ["echo", "1.1.1" ]
}

locals {
  new_version = data.external-raw.new-version.result
}


source "null" "example" {
  communicator = "none"
}

build {
  sources = ["source.null.example"]

  provisioner "shell-local" {
    inline = [
      "echo The New Version is ${local.new_version}",
    ]
  }
}
```

**Comment by DevopsMercenary** [comment]
The setting of the `image_version` fails everytime.

Debug Logs

https://gist.github.com/DevopsMercenary/e62a3a8316212e448975e632e6fb9488

**Comment by lbajolet-hashicorp** [comment]
Looking at the logs and the code, I wonder if the extra `\n` output from `echo` is the culprit here.
Could you try with an `echo -n` for the datasource?
The plugin doesn't trim spaces for this, and the regex doesn't account for extra whitespace before/after, so this could be the problem here.

**Comment by DevopsMercenary** [comment]
Updating the example

```
data "external-raw" "new-version" {
  program = ["echo", "-n", "1.1.1" ]
}
```

Yes, that does resolve this issue.

Thank you for you time and assistance

**Comment by lbajolet-hashicorp** [comment]
Nice, thanks for the update @DevopsMercenary,

I'll relabel the issue as question/not-a-bug and close it now then since it solved the problem for you.

Feel free to reopen if I did this too early, thanks!
