### ISSUE TITLE
packer -force azure-arm crashed "disk with name datadisk-1 already exists in Resource Group"

### ISSUE THREAD

**Issue by J00MZ** [hashicorp/packer-plugin-azure#98]
- `Packer v1.3.5`
- `Linux 4.4.0-1065-aws, Ubuntu 16.04.6 LTS`

Running `packer -force` via shell build step in Jenkins

`packer build -force -var-file=conf/azure.json -only=azure-arm packer.json`
  
failure RC is existing disk 'datadisk-1'
  
However, I'm reporting this since I got the below message:  
```
16:32:48 !!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
16:32:48 
16:32:48 Packer crashed! This is always indicative of a bug within Packer.
16:32:48 A crash log has been placed at "crash.log" relative to your current
16:32:48 working directory. It would be immensely helpful if you could please
16:32:48 report the crash with Packer[1] so that we can fix this.
16:32:48 
16:32:48 [1]: https://github.com/hashicorp/packer/issues
16:32:48 
16:32:48 !!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

- packer.json [here](https://gist.github.com/J00MZ/5cd719f1416aeb623de841d22d3a101c#file-packer-json)
- azure.json [here](https://gist.github.com/J00MZ/e5171c3821fcde730fcdc1a1f598c885#file-azure-json)
- crash.log [here](https://gist.github.com/J00MZ/f2aa034aa59739db83256ee34f1d331e#file-crash-log)

**Comment by JenGoldstrich** [comment]
I believe this issue is stale and no longer applies, if you are still experiencing this error in 2023 and want us to take a look, please open a new issue trying with the newest versions of Packer, and the Azure Plugin.
